# See https://docs.helix-editor.com/configuration.html for options
theme = "dracula_jump"

[editor]
bufferline = "multiple"
true-color = true
line-number = "relative" # shows relative unless unfocused window or in insert mode
rulers = [80,120]
#insert = "bar"

[editor.file-picker]
hidden = false # "Ignore hidden" is a better key here.

[editor.statusline]
right = ["diagnostics", "selections", "position", "file-encoding", "version-control"]

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true
